# Wildcard certificate trigger for isnadboy.com
# This router triggers the generation of a wildcard certificate

http:
  routers:
    # Simple router that triggers wildcard certificate generation
    wildcard-trigger:
      rule: "Host(`isnadboy.com`)"
      service: noop-service
      priority: 1  # Low priority
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
        domains:
          - main: "isnadboy.com"
            sans:
              - "*.isnadboy.com"

  services:
    # Dummy service for the trigger router
    noop-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8080"  # Point to Traefik dashboard