# Wildcard certificate configuration for isnadboy.com
# This requests a single wildcard certificate that covers all subdomains

http:
  routers:
    # Catch-all router to trigger wildcard certificate generation
    wildcard-cert-router:
      rule: "HostRegexp(`{subdomain:[a-z0-9-]+}.isnadboy.com`)"
      service: noop-service
      priority: 1  # Low priority so specific routers take precedence
      tls:
        certResolver: letsencrypt
        domains:
          - main: "isnadboy.com"
            sans:
              - "*.isnadboy.com"

  services:
    # Dummy service for the wildcard router
    noop-service:
      loadBalancer:
        servers:
          - url: "http://localhost"