services:
  # SB Traefik HTTP Provider Service
  sb-traefik-http-provider:
    image: snadboy/sb-traefik-http-provider:latest
    container_name: sb-traefik-http-provider
    restart: unless-stopped
    ports:
      - "8081:8080"  # HTTP provider endpoint
      - "9090:9090"  # Prometheus metrics (optional)
    volumes:
      - ./config/provider-config.yaml:/app/config/provider-config.yaml:ro
      - ./config/ssh-hosts.yaml:/app/config/ssh-hosts.yaml:ro
      - ./config/static-routes.yaml:/app/config/static-routes.yaml:ro  # Optional: static routes
      - ./ssh-keys:/app/ssh-keys:ro  # SSH keys for remote Docker hosts
      - ./logs:/var/log/sb-traefik-provider  # Persistent log storage
    environment:
      - LOG_LEVEL=INFO
      - LOG_DIR=/var/log/sb-traefik-provider
      - LOG_JSON=false  # Set to true for JSON logging
      - PYTHONUNBUFFERED=1
      - WORKERS=2  # Number of uvicorn workers
    networks:
      - traefik
    labels:
      - "snadboy.revp.8080.domain=sb-traefik-provider-api.example.com"
      - "snadboy.revp.9090.domain=sb-traefik-provider-metrics.example.com"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Traefik Instance
  traefik:
    image: traefik:v3.2
    container_name: traefik
    restart: unless-stopped
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.http.endpoint=http://sb-traefik-http-provider:8080/api/traefik/config"
      - "--providers.http.pollInterval=30s"
      - "--providers.docker=false"  # Disable Docker provider since we use HTTP provider
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--log.level=INFO"
      - "--ping"
      # Let's Encrypt configuration with Cloudflare DNS challenge
      - "--certificatesresolvers.letsencrypt.acme.email=your-email@example.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      # Uncomment for testing with staging:
      # - "--certificatesresolvers.letsencrypt.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Traefik dashboard
    networks:
      - traefik
    depends_on:
      - sb-traefik-http-provider
    env_file:
      - .env  # Contains CF_DNS_API_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # Optional: for local container discovery
      - ./traefik-dynamic:/etc/traefik/dynamic:ro
      - ./letsencrypt:/letsencrypt  # Let's Encrypt certificate storage
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  traefik:
    driver: bridge
    name: traefik