# SSH Hosts Configuration Example
# Copy to ssh-hosts.yaml and update with your Tailscale hosts
# Note: Tailscale authentication is used - no SSH keys required!
# Ensure Tailscale is installed and SSH is enabled: tailscale up --ssh

defaults:
  user: docker
  port: 22
  enabled: true

hosts:
  # Development environment (Tailscale hostname)
  dev:
    hostname: host-dev.tail-scale.ts.net
    user: docker
    port: 22
    description: Development Docker host
    enabled: true

  # Production environment (Tailscale hostname)
  prod:
    hostname: host-prod.tail-scale.ts.net
    user: docker
    port: 22
    description: Production Docker host
    enabled: true

  # Staging environment (Tailscale hostname or MagicDNS)
  staging:
    hostname: staging.tail-scale.ts.net
    user: docker
    port: 22
    description: Staging Docker host
    enabled: false